/** @type {import('tailwindcss').Config} */
export default {
            darkMode: "class",
            theme: {
                extend: {
                    colors: {
                        "tertiary-container": "#006f4d",
                        "outline-variant": "#c3c5d7",
                        "surface-container": "#ededf8",
                        "on-surface": "#191b23",
                        "on-error-container": "#93000a",
                        "inverse-surface": "#2e3039",
                        "on-tertiary": "#ffffff",
                        "secondary-fixed": "#d9e3f4",
                        "tertiary-fixed-dim": "#68dba9",
                        "on-background": "#191b23",
                        "on-error": "#ffffff",
                        "on-surface-variant": "#434654",
                        "on-primary-fixed": "#00174d",
                        "tertiary": "#005439",
                        "error-container": "#ffdad6",
                        "secondary": "#555f6d",
                        "inverse-primary": "#b5c4ff",
                        "on-secondary": "#ffffff",
                        "inverse-on-surface": "#f0f0fb",
                        "surface": "#faf8ff",
                        "surface-container-high": "#e7e7f3",
                        "on-primary-fixed-variant": "#003dab",
                        "primary-container": "#1a56db",
                        "on-primary-container": "#d4dcff",
                        "primary": "#003fb1",
                        "surface-bright": "#faf8ff",
                        "surface-dim": "#d9d9e4",
                        "on-secondary-fixed": "#121c28",
                        "on-secondary-fixed-variant": "#3e4755",
                        "on-primary": "#ffffff",
                        "on-tertiary-container": "#7ff2be",
                        "background": "#faf8ff",
                        "on-tertiary-fixed": "#002114",
                        "on-tertiary-fixed-variant": "#005137",
                        "surface-container-highest": "#e2e1ed",
                        "secondary-container": "#d6e0f1",
                        "surface-tint": "#1353d8",
                        "on-secondary-container": "#596372",
                        "error": "#ba1a1a",
                        "primary-fixed": "#dbe1ff",
                        "secondary-fixed-dim": "#bdc7d8",
                        "surface-variant": "#e2e1ed",
                        "surface-container-lowest": "#ffffff",
                        "primary-fixed-dim": "#b5c4ff",
                        "surface-container-low": "#f3f3fe",
                        "outline": "#737686",
                        "tertiary-fixed": "#85f8c4"
                    },
                    fontFamily: {
                        "headline": ["Manrope"],
                        "body": ["Inter"],
                        "label": ["Inter"]
                    },
                    borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
                },
            },
        };
